### ISSUE TITLE
Don't show notification for selected apps

### ISSUE THREAD

**Issue by NikunjKhangwal** [F0x1d/LogFox#116]
I have debloated my phone so this one ad service keep crashing and Logfox shows me notification throughout the day. When I plug charger, switch apps & play music etc, i get dozen of notifications every day. This adservice doesn't really have any app as i can't get into app info page through logfox or other apps. The OEM somehow baked it into the system. I can't completely disable the crash notification for obvious reasons. Is it possible to implement something like this where we can select service which we don't want to see notification of?

![IMG_20240330_175302](https://github.com/F0x1d/LogFox/assets/99175083/0b4cb2dc-1d86-4dae-aa9d-a262fa1edabd)

**Comment by F0x1d** [comment]
A good point, it will be added some day. But currently I can't give any ETAs

**Comment by NikunjKhangwal** [comment]
That's Fine. Take your time.

**Comment by F0x1d** [comment]
Done in v2.0.0

**Comment by NikunjKhangwal** [comment]
Thanks a lot

**Comment by NikunjKhangwal** [comment]
Hey! Do you think you can publish the app on either play store or izzyondroid repo? Main reason for asking this is because froid builds app from source and hence the updates are always massively delayed. The latest version had been out for 4 days but it's still not available on fdroid. Installing github release isn't possible because of different signing keys. Izzy usually provides updates in less than 24 hours and is free.

**Comment by F0x1d** [comment]
Can you open another issue for?

**Comment by NikunjKhangwal** [comment]
Sure #133
